Add kerberos support
opensearch-project/opensearch-py pull request #214
Opened 2022-10-06 12:40 UTC by psaiz

### Description
Provide kerberos authentication support to connect to clusters

### Issues Resolved
This pull request creates a new connection class that extends the HTTP connection to support kerberos. Thanks to it, using the code below, the user can connect using kerberos for authentication:

```
from opensearchpy import OpenSearch
from opensearchpy.connection.krb_requests  import RequestsKrbConnection

client = OpenSearch(["https://<host>/"], connection_class=RequestsKrbConnection)
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-07 17:42 UTC, harshavamsi commented
Hi @psaiz, thanks for the contribution. A couple of thoughts.

We need to get DCO check to pass, so could you sign off your commit with the `-s` flag.

I noticed you're importing `kerberos`, I believe we would need to include it as a dependency to be installed in `setup.py`

We would need unit tests to make sure that this works for both sync and async connections. This ensures test compatibility. 

And it would be great if you could add this class to the `docs` folder so that we can auto generate docs.

2022-10-11 13:29 UTC, psaiz commented
Hi @harshavamsi, 
Thanks for your comments. I'll do the docs and I'll look into the tests and the -s flag, thanks!

About adding kerberos as a dependency, what would you think about making it an [optional dependency](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies)? I mean, the opensearch-py can still be used without kerberos. 
Thanks again ,

Pablo

2022-10-11 17:25 UTC, dblock commented
> Regarding the testing, I'm not sure how to proceed. Note that to test it properly it requires a kerberos setup, and I'm afraid that won't be available during the pipelines. I've checked how it is done in the [pykerberos](https://github.com/bgamble/pykerberos), and they give a test.py file that should be run against their system. Is that what you have in mind?

At least exercise the code to _some_ extent. Mock the kerberos setup.

2022-10-12 13:19 UTC, psaiz commented
Hi @dblock, 
Thanks for the message. Here you have a very basic unittest mocking the kerberos calls.  Let me know if this is what you had in mind.

Best, 
pablo

2022-10-14 19:46 UTC, dblock requested changes
Close!

I made some other comments a bit more in-depth.

2022-10-14 19:46 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +Class for the kerberos authentication.
Nit: "Implements a connection with Kerberos authentication support." (cause we know it's a class ;))

2022-10-14 19:46 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +During the connection phase, one header is added with the kerberos context
Adds an Authorization header during ...

2022-10-14 19:46 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +                 opaque_id=None,
Why is set of arguments different from the super class? Aren't we introducing defaults where we shouldn't?

2022-10-14 19:46 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +            warnings.warn(f"Cannot connect to the realm {principal}")
Include message here too in the `warn`?

2022-10-14 19:46 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +        except Exception as message: # pylint: disable=broad-except
1. Why do we swallow exceptions here to raise something more generic?
2. Is there a way to preserve the inner exception in the re-raised exception?

2022-10-14 19:46 UTC, dblock commented on test_opensearchpy/test_krbconnection.py
> +        self.assertTrue('Authorization' in my_object.session.headers)
Good start. Mock a little further, ensure that the `kerberos.` methods are called, and add a check for the value, it should be "Negotiate [dummy token returned from a mock]" or something like that.

2022-10-19 12:44 UTC, dblock requested changes
I have some more. I know it's just a small piece of code, but let's get it right! Thanks for hanging in here with me.

2022-10-19 12:44 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +                 http_auth=None,
This looks unused, what's `http_auth`?

2022-10-19 12:44 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +        """do the kerberos magic"""
Let's write a useful comment or remove ;) It's no magic.

2022-10-19 12:44 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +            warnings.warn(f"Cannot connect to the realm {principal}. More details: {message}")
Showing client-side warnings isn't a pattern in opensearch-py, I couldn't find another place where this is done. I suppose `GSSError` contains enough information about the problem, just let it be? And what is the reason to wrap all exceptions into `ValueError`?

2022-10-19 12:44 UTC, dblock commented on opensearchpy/connection/krb_requests.py
> +            warnings.warn(f"Could not get the kerberos connection details")
Remove the warning.

2022-10-19 12:44 UTC, dblock commented on test_opensearchpy/test_krbconnection.py
> +        authGSSClientResponse.return_value = "Mocking the response"
Nit: make `return_value` similar to what's typically returned, e.g. `"Negotiate token"`.

2022-10-20 06:56 UTC, psaiz commented
Thanks @dblock ! I'm happy to do as many changes as are needed, so please, keep the comments coming. 

I left a reply in the three open discussions. Please, let me know if those are enough to resolve them.

2022-10-20 16:08 UTC, dblock commented
> Thanks @dblock ! I'm happy to do as many changes as are needed, so please, keep the comments coming.
> 
> I left a reply in the three open discussions. Please, let me know if those are enough to resolve them.

Thanks. See my two comments above, the unused variable is definitely a bug.

2022-10-21 07:20 UTC, aiudirog commented
@psaiz Have you considered just leveraging a standard Kerberos authentication library for requests like [`requests-gssapi`](https://pypi.org/project/requests-gssapi/) or [`requests-kerberos`](https://pypi.org/project/requests-kerberos/)? If so, is there a particular reason you don't want to use them?

If you haven't, you should be able to use them this way:

```python
from opensearchpy import OpenSearch, RequestsHttpConnection
from requests_gssapi import HTTPSPNEGOAuth

opensearch = OpenSearch(
    ...,
    connection_class=RequestsHttpConnection,
    http_auth=HTTPSPNEGOAuth(),
)
```

This is similar to the standard mechanism for [authenticating with AWS IAM roles](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html#request-signing-python).

Making dedicated `Connection` implementations for every combination of HTTP client and authentication mechanism is an N^2 problem that could get out of hand pretty quickly, especially when most clients already have a standard authentication API.

Some of my personal projects are a [port of requests-gssapi to HTTPX](https://github.com/pythongssapi/httpx-gssapi) and adding Windows support to the Python [`gssapi`](https://pypi.org/project/gssapi/1.8.1/) client, so I know my way around this scene a bit.

2022-10-21 13:53 UTC, psaiz commented
Hi @aiudirog, thanks for the input. If that approach works, it is indeed much better than creating a new class. Let me play with it and see if it works in my case.

2022-10-21 16:44 UTC, dblock commented
Either way, I'd appreciate contributions to https://github.com/opensearch-project/opensearch-py/blob/main/GETTING_STARTED.md for this, please! We might also want to rename that to USER_GUIDE to match other clients, cc: @wbeckler - is there a campaign to standardize those things?

2022-10-31 15:28 UTC, aiudirog commented
Can you give the `requests_kerberos` library a try? That one uses pykerberos directly and I'm curious if the issue is GSSAPI or requests' handling of the auth.

2022-11-01 10:31 UTC, psaiz commented
Hi @aiudirog ,

The `requests_kerberos` worked, thanks! In my case, something like:
```
from opensearchpy import OpenSearch, RequestsHttpConnection
import requests_kerberos
url = 'htps://...'
certpath = '/etc/...'
client = OpenSearch([url],
                   use_ssl=True,
                   verify_certs=True,
                   ca_certs=certpath,
                   connection_class=RequestsHttpConnection,
http_auth=requests_kerberos.HTTPKerberosAuth(mutual_authentication=requests_kerberos.OPTIONAL)
```
did the trick. And, once I knew the parameters for the mutual_authentication, I went back to `requests_gssapi`, and 
```
...
from requests_gssapi import HTTPSPNEGOAuth, OPTIONAL
...
client = OpenSearch([url],
 ...
http_auth=HTTPSPNEGOAuth(mutual_authentication=OPTIONAL),
)
```
also worked. 

So, indeed, the new class makes no sense. Following the comment from @dblock, I'll change this MR to update the documentation. I was thinking about leaving in a test (mocking the calls), and the optional dependency for the python_requests. Please, let me know if you want me to remove those as well.

2022-11-09 18:27 UTC, dblock requested changes
The docs are great, and I would be down with just merging that. 

You correctly point out that the test doesn't quite test that the kerberos auth instance is actually called. What else does `send` call? Is there a way to mock those other things? If it's too difficult, then I think we should just remove it. We don't need to test other people's code really, and I believe we already have tests for `http_auth` being used (or we should have some).

2022-11-09 18:27 UTC, dblock commented on USER_GUIDE.md
> +There are several python packages that provide kerberos support over http connections, like [requests-kerberos](http://pypi.org/project/requests-kerberos) and [requests-gssapi](https://pypi.org/proje
capitalize Kerberos

2022-11-09 18:27 UTC, dblock commented on USER_GUIDE.md
> +There are several python packages that provide kerberos support over http connections, like [requests-kerberos](http://pypi.org/project/requests-kerberos) and [requests-gssapi](https://pypi.org/proje
change `like the` to `such as mutual_...`

2022-11-09 18:27 UTC, dblock commented on USER_GUIDE.md
> +    [url],
nit: since URL is not reused, just put it into the parameters

```python
client = OpenSearch(
    ['https://...'],
```

2022-11-09 18:27 UTC, dblock commented on USER_GUIDE.md
> +print(health)
I would remove `print()` ;)

2022-11-10 11:55 UTC, psaiz commented
Thanks @dblock, changed applied, and test removed

2022-11-15 19:33 UTC, dblock requested changes
The only must have is schemas -> schemes (or methods). Schemas means something else.

Thanks for hanging in here with me! Really appreciate your help.

2022-11-15 19:33 UTC, dblock commented on USER_GUIDE.md
> +## Using different authentication schemas
It's "scheme" vs. "schema", but I think you mean "methods"

Btw, maybe we can align the Capitalization of Titles in this PR in the guide? We say "Using Kerberos", but also "Using IAM credentials".

2022-11-15 19:33 UTC, dblock commented on USER_GUIDE.md
> +It is possible to use different schemas for the authentication to OpenSearch. The parameters of `connection_class` and `http_auth` can be used for this. As an example, here we have how to authenticat
schemas -> methods

As an example, here we have -> The following example shows how to authenticate using IAM credentials via Kerberos.

2022-11-15 19:33 UTC, dblock commented on USER_GUIDE.md
> +There are several python packages that provide Kerberos support over http connections, like [requests-kerberos](http://pypi.org/project/requests-kerberos) and [requests-gssapi](https://pypi.org/proje
http -> HTTP

like -> such as

2022-11-22 14:42 UTC, psaiz commented
Thanks @dblock, ready for the next round

2022-11-23 19:01 UTC, dblock approved these changes

2022-11-23 19:02 UTC, dblock commented on USER_GUIDE.md
> +- [Getting started with the OpenSearch python client](#getting-started-with-the-opensearch-python-client)
I think Python is spelled Capital, but I'll merge as is. 

My biggest gripe with this file is those `** ***` titles ;)

2022-11-23 19:02 UTC, dblock submitted a review, later dismissed

2022-11-24 15:33 UTC, psaiz commented
Ok, sorry that I closed it. I've merged it with the changes that had happened in the mean time, and added a line to the Changelog, since one of the workflows was failing

2022-11-28 19:38 UTC, dblock approved these changes

2022-11-28 19:39 UTC, dblock commented
@harshavamsi @VachaShah 2nd pls? Let's merge this?

2022-12-01 19:22 UTC, harshavamsi approved these changes

2022-12-01 19:22 UTC, merged