Include parsed error info in TransportError in async connections
opensearch-project/opensearch-py pull request #226
Opened 2022-10-26 14:55 UTC by gg-kialo

Fixes #225

Signed-off-by: Gordon Govan <gg@kialo.com>

### Description
Parses the error into the `info` field of `TransportException`s in the async connection to match the behaviour of the sync connection.

### Issues Resolved
Closes #225 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-26 15:34 UTC, dblock requested changes
How does this include the error info? I see you add content-type.

Either way needs a test, please.

2022-10-26 15:34 UTC, dblock commented on CHANGELOG.md
> +- Include parsed error info in TransportError in async connections (TODO)
Add a link here to the PR 

```
([#226](https://github.com/opensearch-project/opensearch-py/pull/226))
```

2023-05-03 06:49 UTC, gg-kialo commented
Any hints as to where I could add a test? https://github.com/opensearch-project/opensearch-py/blob/main/test_opensearchpy/test_async/test_connection.py would seem like a good choice, but those tests are using httpbin.org, which doesn't provide an endpoint that returns both a error code and a json body.

2023-05-03 21:17 UTC, dblock commented
> Any hints as to where I could add a test? https://github.com/opensearch-project/opensearch-py/blob/main/test_opensearchpy/test_async/test_connection.py would seem like a good choice, but those tests are using httpbin.org, which doesn't provide an endpoint that returns both a error code and a json body.

I generally have a very dumb approach to this, so a change in `opensearchpy/_async/http_aiohttp.py` should be tested in `.../_async/test_http_aiohttp.py`.

2023-05-04 20:35 UTC, dblock approved these changes

2023-05-04 20:36 UTC, dblock requested changes
One more. I see places (e.g. https://github.com/opensearch-project/opensearch-py/blob/2abb8c43171c2d440d76d26b42972a4bd72996c2/opensearchpy/transport.py#L420) where we do lowercase content-type. Is the map not case-sensitive? Is it always `Content-Type`?

2023-05-08 07:13 UTC, gg-kialo commented
@dblock, yes, `headers` is a `CIMultiDictProxy` (where CI is case-insensitive).

2023-05-09 17:52 UTC, dblock approved these changes

2023-05-09 19:16 UTC, merged