Create bulk.md
opensearch-project/opensearch-py pull request #361
Opened 2023-04-06 15:52 UTC by anabeel011

Resolves issue #354

### Description

This PR adds a guides folder and adds documentation for bulk.

Referenced sources for this change:
- [Ruby Guide](https://github.com/opensearch-project/opensearch-ruby/blob/main/guides/bulk.md)
- [User Guide](https://github.com/opensearch-project/opensearch-py/blob/main/USER_GUIDE.md#creating-a-client)

### Change log:
- created a guides folder
- created bulk.md

Signed-off-by: Ahmad Mohsin <anabeel011@gmail.com>

### Issues Resolved
- Closes #354 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-18 02:48 UTC, VachaShah reviewed
Can you add a Changelog entry for this?

2023-04-19 00:34 UTC, anabeel011 commented
Hi @VachaShah, thanks for taking a look. I tried adding it but for some reason I couldn't see it in changed files. It'd be great if you can provide some steps that I can follow to add a change log entry. I guess I missed a step somewhere :(

2023-04-19 02:07 UTC, anabeel011 commented
Hi @VachaShah, added the change log entry :)

2023-04-20 20:46 UTC, anabeel011 commented
@dblock you are correct, I did notice the bulk section in USER_GUIDE. This is pre-existing though. I intentionally didn't remove that section. 
This was my thought behind not removing the bulk section from USER_GUIDE:
Since this section has been there, users must have referred to it at some point, so I thought it would be helpful to keep it around and remove it once the new `guides` folder has been in existence for (maybe) two releases. So users can have enough time to familiarize with the new `guides` directory and can still refer to the old place they used to refer to.

Do you want me to remove `bulk` section from `USER_GUIDE`?

I think linking this new `bulk` guide in the `USER_GUIDE` would be great, this way users will be able to refer to the old guide and the new guide. 
What are your thoughts?

2023-04-21 16:46 UTC, dblock commented
I think we can consolidate now or later, you decide.

2023-04-25 21:14 UTC, anabeel011 commented
Hi @dblock I consolidated the `bulk` part of `USER_GUIDE`.

2023-05-14 22:50 UTC, anabeel011 commented
Hi! It'd be great to get some review here. Thanks!

2023-06-05 18:28 UTC, saimedhi requested changes

2023-06-05 18:28 UTC, saimedhi commented on guides/bulk.md
> +client.indices.create(movies) if not client.indices.exists(movies)
Slight modifications are needed here because the code is throwing errors.

2023-06-05 18:28 UTC, saimedhi commented on guides/bulk.md
> +```
Please correct me if I am wrong, above code is giving illegal_argument_exception. I tried with opensearch-py 2.2.0

2023-06-05 18:28 UTC, saimedhi commented on guides/bulk.md
> +client.indices.delete("index": ["movies", "books"])
@anabeel011, correct me if I am wrong. Above code didn't work for me. But instead this worked
`client.indices.delete(index= ["movies", "books"])`

2023-06-05 18:32 UTC, saimedhi commented
@anabeel011, Thank you for contributing to opensearch-py. Please merge all the commits into a single commit.

2023-07-25 16:37 UTC, dblock commented
The docs here have a lot of examples that don't work :( 

Superseded with https://github.com/opensearch-project/opensearch-py/pull/448.

2023-07-25 16:37 UTC, closed without merging