[CCI] Create document lifecycle guide
opensearch-project/opensearch-py pull request #364
Opened 2023-04-08 20:01 UTC by Nicksqain

### Description

- [x] Create document lifecycle guide
- [ ] 
### Issues Resolved
#352

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-05 18:56 UTC, saimedhi commented
Hello @Nicksqain, please merge all the commits into a single commit. Thanks.

2023-06-05 22:41 UTC, saimedhi requested changes

2023-06-05 22:41 UTC, saimedhi commented on guides/document_lifecycle.md
> +# OR client.index(index=index, body={"title": "The Lion King 2", "year": 1998})
The commented code worked.

2023-08-03 15:49 UTC, Nicksqain commented
@dblock Yes, I'll be sure to add the necessary changes on a free day!

2023-11-09 22:04 UTC, dblock commented
Superseded with https://github.com/opensearch-project/opensearch-py/pull/559.

2023-11-09 22:04 UTC, closed without merging