Test
opensearch-project/opensearch-py pull request #371
Opened 2023-04-18 13:34 UTC by margulanz

### Description
Updated connection_pool.py, so TypeError does not occur. Updated tests accordingly. I am not sure if this is the best solution, so I am waiting for the advices if there is something wrong with my solution

### Issues Resolved
Partially Closes [347](https://github.com/opensearch-project/opensearch-py/issues/347). 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-18 16:14 UTC, dblock requested changes
This changes what we put into the connection pool `dead` set, which in a way changes an interface. Probably not the best solution, so let's think about it a bit more. What's the actual problem? Are you able to explain why the test fails only on Windows?

Add Windows CI into this PR?

2023-04-18 16:14 UTC, dblock commented on opensearchpy/connection_pool.py
> +            self.dead.put((now + timeout,id(connection),connection))
add a space before `,`

2023-07-19 20:20 UTC, saimedhi commented
Hey @margulanz, Could you kindly answer the questions mentioned above? Thanks :)

2023-08-29 19:42 UTC, saimedhi commented
@margulanz, Could you please respond to the above comments when you have a moment? Thank you!

2023-11-09 23:37 UTC, dblock commented
This seems to have been a red herring, fixed windows CI in https://github.com/opensearch-project/opensearch-py/pull/569.

2023-11-09 23:37 UTC, closed without merging