[#387] Do not escape the "timeout" parameter.
opensearch-project/opensearch-py pull request #394
Opened 2023-05-16 21:28 UTC by grechaw

When the "timeout" parameter is escaped and turned into a string, it does not pass validation checks.
This PR ensures that timeout is passed through as-is, just like "request_timeout".
There's no explicit test for this parameter, but I included it on some existing tests just to ensure that the code is exercised.  Without the fix in place, one of the tests as modified will not pass.

### Description
With this change, using the `timeout` parameter in `cluster.health` no longer throws a validation error.  I have not checked whether the problem exists elsewhere.

### Issues Resolved
Resolves #387 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-05-18 18:57 UTC, grechaw commented
Based on feedback from my colleagues, I'll improve the testing.

2023-05-18 20:51 UTC, dblock requested changes
- add to CHANGELOG, this fixes a bug I think
- you mention there's no unit test - try adding one that is scoped to the `utils` implementation for this?

2023-05-18 23:55 UTC, grechaw commented
Thanks for taking a look @dblock , I've added a simple test and I think this PR will help us move forward.  We have been moving to `opensearch-py` from a very old version of the Elasticsearch client.

2023-05-21 15:57 UTC, dblock approved these changes
Great. This is good with me, but since you're here, extend this test to the other parameters (ignore and request_timeout)? I want to make sure we don't introduce regressions. You'll have to fix `nox lint` as well, please.

2023-05-21 15:57 UTC, dblock commented on CHANGELOG.md
> +- Fix bug with validation of 'timeout' parameter ([#387](Do not escape the "timeout" parameter.))
Re-add the space ;)

2023-05-22 17:33 UTC, grechaw commented
OK thanks again @dblock perhaps we are ready to go.   We all find the 'request_timeout' clobbering action odd, and I'm not sure what the 'ignore' parameter is for, but they're both under test now.

2023-05-23 15:27 UTC, dblock approved these changes

2023-05-23 15:28 UTC, dblock commented
LGTM! Thanks for hanging in here with me. 

Kicked integration tests again, we need to fix this flakiness ...

2023-05-23 20:55 UTC, grechaw commented
It's my pleasure.  I will keep my eye out for more things to address.  Where possible it will be good to migrate more of our code to the `opensearch-py` implementation.    I'll look forward to the next release.

2023-05-23 22:09 UTC, dblock commented
> It's my pleasure. I will keep my eye out for more things to address. Where possible it will be good to migrate more of our code to the `opensearch-py` implementation. I'll look forward to the next release.

If you want something meaty, I suggest https://github.com/opensearch-project/opensearch-py/issues/393 ;)

2023-05-23 22:12 UTC, merged