Index State Management support
opensearch-project/opensearch-py pull request #398
Opened 2023-05-25 11:02 UTC by florianvazelle

### Description
Added support for the ISM API.

### Issues Resolved
The issue of managing index states from the python client.  
This issue is the subject of a feature request at https://github.com/opensearch-project/opensearch-py/issues/284.

2023-06-21 11:34 UTC, florianvazelle commented
Hi @saimedhi, some tests seems to start opensearch without ISM plugin. Is this normal ?

https://github.com/opensearch-project/opensearch-py/actions/runs/5333494406/jobs/9664033038

2023-06-21 17:35 UTC, saimedhi commented
Hi @florianvazelle, I am not completely sure but I suggest to take a look at other existing plugin tests. I have gone through Alerting plugin tests. They are passing for "integration" tests and skipped for "Integration with Unreleased Opensearch" tests. So, please take a look at those tests once. Thanks :)

2023-06-26 23:03 UTC, dblock requested changes
Small request to move plugin tests into separate file(s). Please do for existing ones if this isn't the case.

2023-06-26 23:03 UTC, dblock commented on test_opensearchpy/test_server/test_plugins.py
> +class TestIndexManagementPlugin(OpenSearchTestCase):
We should break tests for each plugin in their own file(s), this is going to get really big.

2023-06-27 15:02 UTC, dblock commented
Looks good, needs a rebase + user guides.

2023-06-28 07:55 UTC, florianvazelle commented
@dblock done ! :slightly_smiling_face:

2023-06-28 20:55 UTC, dblock approved these changes

2023-06-28 20:55 UTC, dblock commented on USER_GUIDE.md
>        - [**Acknowledge alerts**](#acknowledge-alerts)
Mind fixing these `**` in another PR? Thanks.

2023-06-28 20:56 UTC, merged