Security plugin support
opensearch-project/opensearch-py pull request #399
Opened 2023-05-29 15:24 UTC by florianvazelle

### Description
Added support for the Security API.

### Issues Resolved
The issue of managing roles, users... from the python client.  
This issue is the subject of a feature request at https://github.com/opensearch-project/opensearch-py/issues/110.

2023-06-20 12:43 UTC, dblock reviewed
Looks good!

Can we add something to https://github.com/opensearch-project/opensearch-py/blob/main/USER_GUIDE.md#using-plugins as part of this PR?

2023-06-21 09:17 UTC, florianvazelle commented
I pushed some new commits to fix my tests that never passed, because I hadn't quite understood the test suite, which isn't very clear. I added the tests in an async version. 

Yes, I can add something to the USER_GUIDE, but the security API has a lot of enpoints, if I add examples for users and roles, is that enough?

2023-06-26 23:05 UTC, dblock requested changes
Looks great! Split out security plugin tests in its own file(s). Otherwise I think this is good enough.

2023-06-26 23:05 UTC, dblock commented on .ci/run-opensearch.sh
> +      --env "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g" \
Thanks for this.

2023-06-26 23:05 UTC, dblock commented on CHANGELOG.md
> +- Added support for the Security API ([#399](https://github.com/opensearch-project/opensearch-py/pull/399))
Let's say "security plugin"

2023-06-26 23:05 UTC, dblock commented on USER_GUIDE.md
> +#### **Creating a role**
I think another PR was getting rid of these `**` bolding, let's remove those everywhere?

2023-06-27 15:01 UTC, dblock approved these changes

2023-06-27 15:01 UTC, merged

2023-07-19 21:36 UTC, saimedhi commented
Hello @florianvazelle, can you please move Security Client from plugins to clients. example: (opensearchpy/client/security.py) like in PR https://github.com/opensearch-project/opensearch-py/pull/439. All the security features are considered as part of core features of OS. So, kindly let me know if you are willing to make the following changes. This is crucial and had to be done before next release. Thanks for your contributions.