Update USER_GUIDE.md
opensearch-project/opensearch-py pull request #420
Opened 2023-06-21 06:14 UTC by wbeckler

removed unnecessary bolding in headings in TOC and in headings in body

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-21 15:30 UTC, dblock requested changes
Looks like you didn't update the TOC.

2023-07-19 20:12 UTC, saimedhi commented
> Looks like you didn't update the TOC.

TOC is updated in PR https://github.com/opensearch-project/opensearch-py/pull/416. This commit will be merged into [wbeckler-patch-3](https://github.com/opensearch-project/opensearch-py/tree/wbeckler-patch-3) branch.

2023-07-19 20:23 UTC, dblock approved these changes

2023-07-19 20:23 UTC, dblock commented
Ignoring tests since this is a README change (tests would pass on rebase).

2023-07-19 20:23 UTC, merged