Fixed YAML test runner for failing search/highlight/30_max_analyzed_offset[5] test
opensearch-project/opensearch-py pull request #696
Opened 2024-03-14 22:39 UTC by saimedhi

### Description
Fixed YAML test runner for failing search/highlight/30_max_analyzed_offset[5] test in integration tests against an **unreleased** versions [2.x](https://github.com/opensearch-project/opensearch-py/actions/runs/8246216987/job/22551786241#step:10:2051), [main](https://github.com/opensearch-project/opensearch-py/actions/runs/8246216987/job/22551788126#step:10:2159) of OpenSearch.

- Note: This test is failing in several **released** opensearch versions as well. To address the failing tests in those versions, I'll correct the skipped versions in the [opensearch main branch](https://github.com/opensearch-project/OpenSearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/test/search.highlight/30_max_analyzed_offset.yml#L85). Skip version should be version: " - 2.12.99"

### Issues Resolved
Related to https://github.com/opensearch-project/opensearch-py/issues/686

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-14 22:52 UTC, saimedhi commented
Verified that this PR is not causing additional test failures.

2024-03-15 13:27 UTC, dblock requested changes
Isn't the problem in the test runner that doesn't behaves like other test runners and strips the value? Remove `strip`?

2024-03-16 11:55 UTC, dblock approved these changes

2024-03-16 11:58 UTC, dblock commented
Better. When it's a regex, ignore spaces, otherwise match.

2024-03-16 11:58 UTC, merged