rc corrected to response
opensearch-project/opensearch-py pull request #772
Opened 2024-07-09 20:08 UTC by oconpa

There seems to be a mistype in the code. I believe it's meant to say response

### Description
_Describe what this change achieves._

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-09 20:18 UTC, saimedhi requested changes
@oconpa, thank you for your contribution! Could you please correct rc to response [here](https://github.com/opensearch-project/opensearch-py/pull/772/files#diff-d5bb6aaf04f331a09a13037da85b10a20eeeefb3216f41c52385f748e799e80eR33) as well? Thank you!

2024-07-09 22:25 UTC, oconpa commented
> @oconpa, thank you for your contribution! Could you please correct rc to response [here](https://github.com/opensearch-project/opensearch-py/pull/772/files#diff-d5bb6aaf04f331a09a13037da85b10a20eeeefb3216f41c52385f748e799e80eR33) as well? Thank you!

Corrected good spot

2024-07-09 23:54 UTC, dblock approved these changes

2024-07-12 05:29 UTC, saimedhi approved these changes

2024-07-12 05:30 UTC, merged