Ignore name of index when fetching settings
opensearch-project/opensearch-py pull request #823
Opened 2024-09-18 02:30 UTC by tienne-B

### Description

This commit fixes a situation where an index cannot be updated through this client as the index is aliased, with the client pointing to the alias.

As the `GET /<index>/_settings` request will only ever return the settings for the specified index (through the alias), it would only have one key, so the name of the key would not matter. We can pop the key to get the settings object for the index through the alias.

_Describe what this change achieves._

### Issues Resolved

Closes #822 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-18 16:56 UTC, tienne-B commented
Thank you @dblock for your quick response! The value of removing `self._name` is that saving an index previously wouldn't work if OS-py accesses it through an alias (and using an alias seems to be a good practice for downtime prevention). All the requests that are triggered by the `.save()` method can work transparently through an index, however, when making the `GET /<alias>/_settings` request, the `dict` response key is the name of the true index, rather than the alias. This causes the `KeyError`. However, the data we're extracting doesn't depend on the name, so it'd be safe to disregard and pop the key/value.

If it's wanted, I could add a check that the alias only points to one index to raise a more specific error. Would that be appreciated?

I've added a test, but I'm a little skeptical of the coverage report as it's based off a 6-month-old commit.

Thank you!

2024-09-19 08:12 UTC, dblock commented
> If it's wanted, I could add a check that the alias only points to one index to raise a more specific error. Would that be appreciated?

Possibly, but doesn't have to block this PR. Give it a shot after I merge this!

2024-09-19 08:13 UTC, dblock requested changes
This all makes sense.

I think you have to do the same for the async code (see https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/_async/helpers/index.py#L308). Add a test for that too.

2024-09-20 11:47 UTC, tienne-B commented
I've added support for async, the checks for multiple indices, and testing for these.

2024-09-23 12:25 UTC, dblock requested changes
Looks good! 

I have some small language asks for the error. Also check that the tests do run because CodeCov seems unhappy and complains that tests are missing which seems odd.

2024-09-23 12:25 UTC, dblock commented on opensearchpy/_async/helpers/index.py
> +                "The settings for %s points to many indices: %s"
```suggestion
                "Settings for %s point to multiple indices: %s."
```

2024-09-23 13:34 UTC, tienne-B commented on opensearchpy/helpers/test.py
> +OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://localhost:9200")
Oh sorry, didn't mean to commit that! I had noticed that the tests did not run, and had to uncomment these list values to get the tests to run:

https://github.com/opensearch-project/opensearch-py/blob/a24b9f3f3cccd779ef0d9b1161ce8ce518717d10/test_opensearchpy/run_tests.py#L159-L164

I am a little hesitant to commit such changes as I don't have much context as to why this has been done and if it'd break anything. Also, the base commit for Codecov is quite old.

2024-09-25 02:05 UTC, tienne-B commented on opensearchpy/helpers/test.py
> +OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://localhost:9200")
I can assure you that they do pass locally with the files un-ignored.

On GitHub Actions they would be skipped as there is no OpenSearch service for the tests to use.

2024-09-25 02:09 UTC, tienne-B commented on test_opensearchpy/test_async/test_server/test_helpers/test_index.py
> +    assert False
I'll use `assertRaises`; cleans it up a bit.

2024-09-25 19:54 UTC, dblock commented on opensearchpy/helpers/test.py
> +OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://localhost:9200")
That's the whole point, integration tests should run on GHA in one of the workflows.

2024-09-26 13:21 UTC, tienne-B commented
@dblock Rebased.

2024-09-26 14:44 UTC, dblock requested changes
There's still that http, want to fix it?

2024-09-26 14:44 UTC, dblock commented on opensearchpy/helpers/test.py
> +OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://localhost:9200")
This is still here, do you want to revert this line?

2024-09-26 17:41 UTC, tienne-B commented on opensearchpy/helpers/test.py
> +OPENSEARCH_URL = os.environ.get("OPENSEARCH_URL", "http://localhost:9200")
Reverted, sorry.

2024-09-26 18:02 UTC, dblock approved these changes

2024-09-26 18:02 UTC, merged