Fix bug where URL is being signed after being quoted
opensearch-project/opensearch-py pull request #839
Opened 2024-10-28 17:15 UTC by fabiopedrosa

### Description

URL is being signed after being quoted, but should be before.

### Issues Resolved
Closed https://github.com/opensearch-project/opensearch-py/issues/833

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-28 17:50 UTC, dblock requested changes
I don't think this is the right fix. The URL could have been already quoted before, in which case it will start failing again. Look for where it gets quoted in the first place, and preserve the original URL to be used here for signing. 

Start by writing a failing test, too, and let's make sure it exists for all transport classes.

2024-10-29 12:12 UTC, fabiopedrosa commented
@dblock I agree, I just won't have time to do that work right now.

2024-10-29 19:31 UTC, dblock commented
> @dblock I agree, I just won't have time to do that work right now. Is it something AWS can contribute to?

We can see. Do you have a ticket with customer support by any chance?

2024-11-04 17:18 UTC, besil commented
hello, I just opened a case to AWS support before discovering this thread. If you need it, I can provide the AWS Support Ticket ID

2024-11-25 22:22 UTC, mingshl commented
it seems this ticket is out of dated. can you please close it ?@fabiopedrosa

2024-11-27 22:51 UTC, dblock commented
Fixed in https://github.com/opensearch-project/opensearch-py/pull/848.

2024-11-27 22:51 UTC, closed without merging

2024-11-27 22:52 UTC, dblock commented
@fabiopedrosa If you're relying on the fix you proposed here I suggest reverting to HEAD (and the next release of opensearch-py). This fix doesn't work in half the cases with indices with special characters for example.

2024-11-27 23:46 UTC, fabiopedrosa commented
@dblock just tried using HEAD and works great. thank you a lot for the fixes, and thank you @nathaliellenaa